import { useNoteCanvasRuntime } from './useNoteCanvasRuntime';
import { useRuntimeBlockOperationsController } from './useRuntimeBlockOperationsController';
import { useRuntimeDocumentDataController } from './useRuntimeDocumentDataController';
import { useRuntimeLayoutModelController } from './useRuntimeLayoutModelController';
import { useRuntimePresentationController } from './useRuntimePresentationController';
import { useRuntimeSurfaceStateController } from './useRuntimeSurfaceStateController';

export function useNoteCanvasRuntimeController() {
  const { noteId } = useNoteCanvasRuntime();
  const {
    activeBlockId,
    beginTemporaryLayoutMode,
    blockListRef,
    chromeCollapsed,
    clearTemporaryLayoutMode,
    clearBlockSelection,
    closeOverlay,
    collapseChrome,
    expandChrome,
    focusBlockId,
    interactionState,
    layoutMode,
    layoutModeKind,
    markBlockFocused,
    markBlockSelected,
    movingBlockIdRef,
    openLayoutPanel,
    pageOffsetX,
    panViewportBy,
    resetViewport,
    selectedBlockId,
    scrollViewportBy,
    setActiveBlockId,
    setFocusBlockId,
    setInteractionState,
    setSelectedBlockId,
    setSnapGuide,
    setViewportSize,
    snapEnabled,
    snapGuide,
    showExportPreview,
    showLayoutPanel,
    showMoreActions,
    showNoteInfo,
    showPreviewAIVisibility,
    showPreviewBlockTypes,
    showPreviewExportStatus,
    showPreviewLabelOverlay,
    suppressMeasuredReflowUntilRef,
    surfaceMode,
    surfacePolicy,
    toggleExportPreview,
    toggleLayoutMode,
    toggleMoreActions,
    toggleNoteInfo,
    togglePreviewAIVisibility,
    togglePreviewBlockTypes,
    togglePreviewExportStatus,
    togglePreviewLabelOverlay,
    toggleSnapEnabled,
    toggleSurfaceMode,
    viewportTransform,
    zoomViewportAt,
  } = useRuntimeSurfaceStateController();
  const {
    applyMeasuredBlockHeightDraft,
    note,
    blocks,
    sortedBlocks,
    loading,
    titleDraft,
    setTitleDraft,
    templateOptions,
    templateWarning,
    savingBlockId,
    anchorsBySourceRef,
    sourceJumpTarget,
    setSourceJumpTarget,
    sourceJumpBusy,
    annotationTruths,
    contentGroups,
    groupFolders,
    blockTextDrafts,
    setBlockTextDrafts,
    blockTextFlowDrafts,
    setBlockTextFlowDrafts,
    blockFieldDrafts,
    setBlockFieldDrafts,
    defaultTextTemplate,
    insertTemplateOptions,
    saveTitle,
    saveAnnotationTruths,
    saveContentGroups,
    saveGroupFolders,
    createBlock,
    saveBlock,
    applyTemplateToBlock,
    persistBlockLayout,
    toggleBlockExportRole,
    toggleBlockAIVisibility,
    trashBlock,
    restoreBlock,
    handleViewSource,
    layoutDrafts,
    mergeLayoutDrafts,
    setLayoutDrafts,
    sourceReferenceCount,
  } = useRuntimeDocumentDataController({
    clearBlockSelection,
    noteId,
  });

  const {
    blockLayouts,
    contentWidth,
    defaultDraftLayout,
    persistChangedBlockLayouts,
    persistLayoutSnapshot,
    visibleBlocks,
  } = useRuntimeLayoutModelController({
    blocks,
    blockListRef,
    layoutDrafts,
    pageOffsetX,
    persistBlockLayout,
    sortedBlocks,
    surfaceMode,
    surfacePolicy,
  });

  const {
    activateDraft,
    activeSlashCommandId,
    clearSlashTarget,
    creatingDraft,
    discardDraft,
    draftActive,
    draftLayout,
    draftRef,
    draftText,
    handleBlockKeyDown,
    handleBlockListMouseDown,
    handleBlockTextChange,
    handleDraftChange,
    handleDraftKeyDown,
    handleTrashBlock,
    handlePageSpaceDoubleClick,
    handleSelectSlashCommand,
    handleSurfacePointerDown,
    handleMeasuredBlockHeight,
    persistDraft,
    resizeDraftFromTextarea,
    slashCommands,
    slashTarget,
    updateBlockFieldDraft,
    beginMoveBlock,
    beginResizeBlock,
  } = useRuntimeBlockOperationsController({
    applyLayoutDrafts: mergeLayoutDrafts,
    applyMeasuredBlockHeightDraft,
    applyTemplateToBlock,
    blockLayouts,
    blockListRef,
    blocks,
    blockTextDrafts,
    blockTextFlowDrafts,
    clearBlockSelection,
    contentWidth,
    createBlock,
    defaultDraftLayout,
    defaultTextTemplate,
    insertTemplateOptions,
    movingBlockIdRef,
    note,
    orderedBlocks: visibleBlocks,
    pageOffsetX,
    viewportTransform,
    persistChangedBlockLayouts,
    persistLayoutSnapshot,
    restoreBlockForHistory: restoreBlock,
    saveBlock,
    setBlockFieldDrafts,
    setBlockTextDrafts,
    setBlockTextFlowDrafts,
    setActiveBlockId,
    setFocusBlockId,
    setInteractionState,
    setLayoutDrafts,
    setSelectedBlockId,
    setSnapGuide,
    snapEnabled,
    beginTemporaryLayoutMode,
    clearTemporaryLayoutMode,
    suppressMeasuredReflowUntilRef,
    surfacePolicy,
    templateOptions,
    trashBlock,
  });

  const { layerProps } = useRuntimePresentationController({
    activeBlockId,
    activeSlashCommandId,
    anchorsBySourceRef,
    blockFieldDrafts,
    blockLayouts,
    blockListRef,
    blockTextDrafts,
    blockTextFlowDrafts,
    chromeCollapsed,
    creatingDraft,
    defaultDraftLayout,
    draftActive,
    draftLayout,
    draftRef,
    draftText,
    focusBlockId,
    interactionState,
    layoutMode,
    layoutModeKind,
    note,
    pageOffsetX,
    savingBlockId,
    selectedBlockId,
    setSourceJumpTarget,
    showExportPreview,
    showLayoutPanel,
    showMoreActions,
    showNoteInfo,
    showPreviewAIVisibility,
    showPreviewBlockTypes,
    showPreviewExportStatus,
    showPreviewLabelOverlay,
    slashCommands,
    slashTarget,
    snapEnabled,
    snapGuide,
    sortedBlockCount: sortedBlocks.length,
    sourceJumpBusy,
    sourceJumpTarget,
    annotationTruths,
    contentGroups,
    groupFolders,
    sourceReferenceCount,
    surfaceMode,
    surfacePolicy,
    surfacePolicyMode: surfacePolicy.mode,
    templateWarning,
    titleDraft,
    viewportTransform,
    visibleBlocks,
    onActivateDraft: activateDraft,
    onBeginMoveBlock: beginMoveBlock,
    onBeginResizeBlock: beginResizeBlock,
    onBlockKeyDown: handleBlockKeyDown,
    onBlockListMouseDown: handleBlockListMouseDown,
    onBlockTextChange: handleBlockTextChange,
    onBlockTextFlowChange: setBlockTextFlowDrafts,
    onClearSlashTarget: clearSlashTarget,
    onCloseOverlay: closeOverlay,
    onCollapseChrome: collapseChrome,
    onDiscardDraft: discardDraft,
    onDraftChange: handleDraftChange,
    onDraftKeyDown: handleDraftKeyDown,
    onExpandChrome: expandChrome,
    onFieldDraftChange: updateBlockFieldDraft,
    onFloatingPanelFocusBlock: setFocusBlockId,
    onMeasuredBlockHeight: handleMeasuredBlockHeight,
    onPageSpaceDoubleClick: handlePageSpaceDoubleClick,
    onPersistDraft: (text, options) => persistDraft(text, undefined, options),
    onResizeDraftFromTextarea: resizeDraftFromTextarea,
    onResetViewport: resetViewport,
    onSaveBlock: saveBlock,
    onSaveTitle: saveTitle,
    onSaveAnnotationTruths: saveAnnotationTruths,
    onSaveContentGroups: saveContentGroups,
    onSaveGroupFolders: saveGroupFolders,
    onSelectBlock: markBlockSelected,
    onSelectSlashCommand: handleSelectSlashCommand,
    onSurfacePointerDown: handleSurfacePointerDown,
    onTitleDraftChange: setTitleDraft,
    onToggleAIVisibility: toggleBlockAIVisibility,
    onToggleExportPreview: toggleExportPreview,
    onToggleExportRole: toggleBlockExportRole,
    onToggleLayoutMode: toggleLayoutMode,
    onToggleMoreActions: toggleMoreActions,
    onToggleNoteInfo: toggleNoteInfo,
    onOpenLayoutPanel: openLayoutPanel,
    onTogglePreviewAIVisibility: togglePreviewAIVisibility,
    onTogglePreviewBlockTypes: togglePreviewBlockTypes,
    onTogglePreviewExportStatus: togglePreviewExportStatus,
    onTogglePreviewLabelOverlay: togglePreviewLabelOverlay,
    onToggleSnapEnabled: toggleSnapEnabled,
    onToggleSurfaceMode: toggleSurfaceMode,
    onTrashBlock: handleTrashBlock,
    onPanViewportBy: panViewportBy,
    onScrollViewportBy: scrollViewportBy,
    onViewportSizeChange: setViewportSize,
    onViewSource: handleViewSource,
    onZoomViewportAt: zoomViewportAt,
    onWritingSurfaceFocusBlock: markBlockFocused,
  });

  return {
    layerProps,
    loading,
    note,
  };
}
