import { useCallback } from 'react';
import { useNoteCanvasRuntime } from './useNoteCanvasRuntime';
import { useRuntimeBlockOperationsController } from './useRuntimeBlockOperationsController';
import { useRuntimeDocumentDataController } from './useRuntimeDocumentDataController';
import { useRuntimeLayoutModelController } from './useRuntimeLayoutModelController';
import { useRuntimePresentationController } from './useRuntimePresentationController';
import { useRuntimeSurfaceStateController } from './useRuntimeSurfaceStateController';
import { useBlockTextFlowEditController } from './useBlockTextFlowEditController';
import { useSlashBlockRollbackController } from './useSlashBlockRollbackController';
import { tableObjectSavePayload } from '../tableObjectService';
import type {
  StructuredCanvasObject,
  TableStructuredPayload,
} from '../types';

export function useNoteCanvasRuntimeController() {
  const { noteId } = useNoteCanvasRuntime();
  const {
    activeBlockId,
    beginTemporaryLayoutMode,
    blockListRef,
    chromeCollapsed,
    clearTemporaryLayoutMode,
    clearBlockSelection,
    closeOverlay,
    collapseChrome,
    expandChrome,
    focusBlockId,
    focusedTextOwner,
    focusViewportOnRect,
    interactionState,
    layoutMode,
    layoutModeKind,
    markBlockFocused,
    markDraftFocused,
    markBlockSelected,
    releaseTextFocus,
    movingBlockIdRef,
    openLayoutPanel,
    pageOffsetX,
    panViewportBy,
    resetViewport,
    selectedBlockId,
    scrollViewportBy,
    setActiveBlockId,
    setFocusBlockId,
    setInteractionState,
    setSelectedBlockId,
    setSnapGuide,
    setViewportSize,
    snapEnabled,
    snapGuide,
    showExportPreview,
    showLayoutPanel,
    showMoreActions,
    showNoteInfo,
    showPreviewAIVisibility,
    showPreviewBlockTypes,
    showPreviewExportStatus,
    showPreviewLabelOverlay,
    suppressMeasuredReflowUntilRef,
    surfaceMode,
    surfacePolicy,
    toggleExportPreview,
    toggleLayoutMode,
    toggleMoreActions,
    toggleNoteInfo,
    togglePreviewAIVisibility,
    togglePreviewBlockTypes,
    togglePreviewExportStatus,
    togglePreviewLabelOverlay,
    toggleSnapEnabled,
    toggleSurfaceMode,
    viewportTransform,
    zoomViewportAt,
  } = useRuntimeSurfaceStateController();
  const {
    applyMeasuredBlockHeightDraft,
    note,
    sourceProjectionPolicy,
    blocks,
    sortedBlocks,
    loading,
    titleDraft,
    setTitleDraft,
    templateOptions,
    templateWarning,
    savingBlockId,
    blockEditRecoveryReceipts,
    anchorsBySourceRef,
    sourceJumpTarget,
    setSourceJumpTarget,
    sourceJumpBusy,
    annotationTruths,
    contentGroups,
    groupFolders,
    purposeFrames,
    pageFrameCollection,
    persistedCanvasObjects,
    persistedCanvasPlacements,
    persistedContentMounts,
    persistedVisualConnectors,
    persistedImageObjects,
    persistedStructuredObjects,
    documentTypographyProfile,
    blockTextDrafts,
    setBlockTextDrafts,
    blockTextFlowDrafts,
    setBlockTextFlowDrafts,
    blockFieldDrafts,
    setBlockFieldDrafts,
    readBlockDraftSnapshot,
    defaultTextTemplate,
    insertTemplateOptions,
    saveTitle,
    saveAnnotationTruths,
    saveContentGroups,
    saveGroupFolders,
    savePurposeFrames,
    savePageFrameCollection,
    persistCanvasObject,
    deleteCanvasObject,
    saveDocumentTypographyProfile,
    createBlock,
    createDraftBlock,
    discardDraftBlock,
    finalizeDraftBlock,
    saveBlock,
    applyBlockEditRecovery,
    dismissBlockEditRecovery,
    saveDraftBlockPlacement,
    applyTemplateToBlock,
    persistBlockLayout,
    toggleBlockExportRole,
    toggleBlockAIVisibility,
    trashBlock,
    forgetBlockLocally,
    restoreBlock,
    restoreBlockById,
    handleViewSource,
    layoutDrafts,
    mergeLayoutDrafts,
    setLayoutDrafts,
    sourceReferenceCount,
  } = useRuntimeDocumentDataController({
    clearBlockSelection,
    noteId,
  });

  const persistStructuredObjectForHistory = useCallback(async (
    objectId: string,
    payload: TableStructuredPayload,
  ): Promise<boolean> => {
    const canvasObject = persistedCanvasObjects.find((item) => item.objectId === objectId);
    const placement = persistedCanvasPlacements.find((item) => item.objectId === objectId);
    const structuredObject = persistedStructuredObjects.find((item) => item.objectId === objectId);
    if (!canvasObject || !placement || !structuredObject) return false;
    const nextStructuredObject: StructuredCanvasObject = {
      ...structuredObject,
      rowCount: payload.rows.length,
      columnCount: payload.columns.length,
      payload,
    };
    return persistCanvasObject({
      canvasObject,
      placement,
      contentMounts: [],
      structuredObject: nextStructuredObject,
      payload: tableObjectSavePayload(canvasObject, placement, nextStructuredObject),
    });
  }, [persistCanvasObject, persistedCanvasObjects, persistedCanvasPlacements, persistedStructuredObjects]);

  const {
    blockLayouts,
    contentWidth,
    defaultDraftLayout,
    persistChangedBlockLayouts,
    persistLayoutSnapshot,
    visibleBlocks,
  } = useRuntimeLayoutModelController({
    blocks,
    blockListRef,
    documentTypographyProfile,
    layoutDrafts,
    pageOffsetX,
    persistBlockLayout,
    sortedBlocks,
    surfaceMode,
    surfacePolicy,
  });

  const applyBlockTextFlowEdit = useBlockTextFlowEditController({
    annotationTruths,
    blockTextFlowDrafts,
    saveAnnotationTruths,
    setBlockTextFlowDrafts,
  });
  const rollbackBlockSlashSession = useSlashBlockRollbackController({
    applyBlockTextFlowEdit,
    blocks,
    readBlockDraftSnapshot,
    saveBlock,
    setBlockFieldDrafts,
    setBlockTextDrafts,
  });
  const {
    activateDraft,
    activeSlashCommandId,
    clearSlashTarget,
    creatingDraft,
    discardDraft,
    draftActive,
    draftFocusReceipt,
    draftLayout,
    draftOwnerReconciliation,
    draftPhase,
    draftRef,
    draftText,
    handleBlockKeyDown,
    handleBlockListMouseDown,
    handleBlockTextChange,
    handleDraftChange,
    handleDraftFocusReceipt,
    handleDraftKeyDown,
    handleDurableFocusReceipt,
    handleTrashBlock,
    handlePageSpaceDoubleClick,
    handleSelectSlashCommand,
    handleSurfacePointerDown,
    handleMeasuredBlockHeight,
    placementPending,
    persistDraft,
    pushStructuredMutationHistory,
    resizeDraftFromTextarea,
    slashCommands,
    slashTarget,
    updateBlockFieldDraft,
    beginMoveBlock,
    beginResizeBlock,
  } = useRuntimeBlockOperationsController({
    applyLayoutDrafts: mergeLayoutDrafts,
    applyMeasuredBlockHeightDraft,
    applyTemplateToBlock,
    blockLayouts,
    blockListRef,
    blocks,
    blockTextDrafts,
    blockTextFlowDrafts,
    clearBlockSelection,
    contentWidth,
    createBlock: createDraftBlock,
    defaultDraftLayout,
    defaultTextTemplate,
    discardDraftBlock,
    finalizeDraftBlock,
    documentTypographyProfile,
    insertTemplateOptions,
    movingBlockIdRef,
    note,
    focusedTextOwner,
    onDraftFocusReceipt: markDraftFocused,
    orderedBlocks: visibleBlocks,
    pageOffsetX,
    pageFrameCollection,
    selectedPageFrameId: pageFrameCollection?.selectedFrameId || pageFrameCollection?.primaryFrameId || null,
    viewportTransform,
    persistChangedBlockLayouts,
    persistLayoutSnapshot,
    restoreBlockForHistory: restoreBlock,
    rollbackBlockSlashSession,
    saveBlock,
    saveDraftBlockPlacement,
    persistStructuredObjectForHistory,
    onFocusPageFrame: (pageFrame) => focusViewportOnRect(pageFrame),
    onSavePageFrameCollection: savePageFrameCollection,
    setBlockFieldDrafts,
    setBlockTextDrafts,
    setBlockTextFlowDrafts,
    setActiveBlockId,
    setFocusBlockId,
    setInteractionState,
    setLayoutDrafts,
    setSelectedBlockId,
    setSnapGuide,
    snapEnabled,
    beginTemporaryLayoutMode,
    clearTemporaryLayoutMode,
    suppressMeasuredReflowUntilRef,
    surfacePolicy,
    templateOptions,
    trashBlock,
  });

  const handleWritingSurfaceFocusBlock = useCallback((receipt: Parameters<typeof markBlockFocused>[0]) => {
    markBlockFocused(receipt);
    handleDurableFocusReceipt(receipt);
  }, [handleDurableFocusReceipt, markBlockFocused]);

  const { layerProps } = useRuntimePresentationController({
    activeBlockId,
    activeSlashCommandId,
    anchorsBySourceRef,
    allBlocks: sortedBlocks,
    blockFieldDrafts,
    blockEditRecoveryReceipts,
    blockLayouts,
    blockListRef,
    blockTextDrafts,
    blockTextFlowDrafts,
    chromeCollapsed,
    creatingDraft,
    defaultDraftLayout,
    defaultTextTemplate,
    documentTypographyProfile,
    draftActive,
    draftFocusReceipt,
    draftLayout,
    draftOwnerReconciliation,
    draftPhase,
    draftRef,
    draftText,
    focusBlockId,
    focusedTextOwner,
    interactionState,
    layoutMode,
    layoutModeKind,
    note,
    pageOffsetX,
    pageFrameCollection,
    placementPending,
    persistedCanvasObjects,
    persistedCanvasPlacements,
    persistedContentMounts,
    persistedVisualConnectors,
    persistedImageObjects,
    persistedStructuredObjects,
    contentLookupBlocks: sortedBlocks,
    savingBlockId,
    selectedBlockId,
    setSourceJumpTarget,
    showExportPreview,
    showLayoutPanel,
    showMoreActions,
    showNoteInfo,
    showPreviewAIVisibility,
    showPreviewBlockTypes,
    showPreviewExportStatus,
    showPreviewLabelOverlay,
    slashCommands,
    slashTarget,
    snapEnabled,
    snapGuide,
    sortedBlockCount: sortedBlocks.length,
    sourceJumpBusy,
    sourceJumpTarget,
    annotationTruths,
    contentGroups,
    groupFolders,
    purposeFrames,
    sourceReferenceCount,
    contentReadOnly: sourceProjectionPolicy.contentReadOnly,
    surfaceMode,
    surfacePolicy,
    surfacePolicyMode: surfacePolicy.mode,
    templateWarning,
    titleDraft,
    viewportTransform,
    visibleBlocks,
    onCreateBlock: createBlock,
    onActivateDraft: activateDraft,
    onBeginMoveBlock: beginMoveBlock,
    onBeginResizeBlock: beginResizeBlock,
    onBlockKeyDown: handleBlockKeyDown,
    onBlockListMouseDown: handleBlockListMouseDown,
    onBlockTextChange: handleBlockTextChange,
    onBlockTextFlowChange: setBlockTextFlowDrafts,
    onApplyBlockTextFlowEdit: applyBlockTextFlowEdit,
    onApplyBlockEditRecovery: applyBlockEditRecovery,
    onApplyBlockLayoutDrafts: mergeLayoutDrafts,
    onClearSlashTarget: clearSlashTarget,
    onCloseOverlay: closeOverlay,
    onCollapseChrome: collapseChrome,
    onDiscardDraft: discardDraft,
    onDismissBlockEditRecovery: dismissBlockEditRecovery,
    onDraftChange: handleDraftChange,
    onDraftFocusReceipt: handleDraftFocusReceipt,
    onDraftKeyDown: handleDraftKeyDown,
    onExpandChrome: expandChrome,
    onFieldDraftChange: updateBlockFieldDraft,
    onFocusPageFrame: (pageFrame, world) => focusViewportOnRect(pageFrame, world),
    onReleaseTextFocus: releaseTextFocus,
    onFloatingPanelFocusBlock: setFocusBlockId,
    onMeasuredBlockHeight: handleMeasuredBlockHeight,
    onPageSpaceDoubleClick: handlePageSpaceDoubleClick,
    onPersistDraft: (text, options) => persistDraft(text, undefined, options),
    onPersistChangedBlockLayouts: persistChangedBlockLayouts,
    onResizeDraftFromTextarea: resizeDraftFromTextarea,
    onResetViewport: resetViewport,
    onSaveBlock: saveBlock,
    onSaveTitle: saveTitle,
    onSaveAnnotationTruths: saveAnnotationTruths,
    onSaveContentGroups: saveContentGroups,
    onSaveGroupFolders: saveGroupFolders,
    onSavePurposeFrames: savePurposeFrames,
    onSavePageFrameCollection: savePageFrameCollection,
    onPersistCanvasObject: persistCanvasObject,
    onPushStructuredMutationHistory: pushStructuredMutationHistory,
    onDeleteCanvasObject: deleteCanvasObject,
    onSaveDocumentTypographyProfile: saveDocumentTypographyProfile,
    onSelectBlock: markBlockSelected,
    onSelectSlashCommand: handleSelectSlashCommand,
    onSurfacePointerDown: handleSurfacePointerDown,
    onTitleDraftChange: setTitleDraft,
    onToggleAIVisibility: toggleBlockAIVisibility,
    onToggleExportPreview: toggleExportPreview,
    onToggleExportRole: toggleBlockExportRole,
    onToggleLayoutMode: toggleLayoutMode,
    onToggleMoreActions: toggleMoreActions,
    onToggleNoteInfo: toggleNoteInfo,
    onOpenLayoutPanel: openLayoutPanel,
    onTogglePreviewAIVisibility: togglePreviewAIVisibility,
    onTogglePreviewBlockTypes: togglePreviewBlockTypes,
    onTogglePreviewExportStatus: togglePreviewExportStatus,
    onTogglePreviewLabelOverlay: togglePreviewLabelOverlay,
    onToggleSnapEnabled: toggleSnapEnabled,
    onToggleSurfaceMode: toggleSurfaceMode,
    onTrashBlock: handleTrashBlock,
    onForgetBlockLocally: forgetBlockLocally,
    onRestoreBlockById: restoreBlockById,
    onPanViewportBy: panViewportBy,
    onScrollViewportBy: scrollViewportBy,
    onViewportSizeChange: setViewportSize,
    onViewSource: handleViewSource,
    onZoomViewportAt: zoomViewportAt,
    onWritingSurfaceFocusBlock: handleWritingSurfaceFocusBlock,
    onWritingSurfaceRequestBlockFocus: setFocusBlockId,
  });

  return {
    layerProps,
    loading,
    note,
  };
}
