import { act, renderHook } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { requireCanvasPlacementWritePayload, resolveActiveNoteCanvasMode } from './canvasRetirementPolicy';
import { saveBlockCanvasPlacementForNote, saveGenericCanvasObjectForNote } from './canvasObjectRepository';
import { readStoredLayout } from './placementService';
import { useSurfaceModeController } from './hooks/useSurfaceModeController';
import type { BlockBoxLayout } from './runtimeLayout';

const api = vi.hoisted(() => ({ put: vi.fn() }));
vi.mock('@/services/api', () => ({ default: api }));
const geometry = { x: 12, y: 14, width: 300, height: 72 };

describe('S5 retired canvas doors', () => {
  beforeEach(() => api.put.mockReset());

  it('opens legacy canvas route/state as Page and keeps it Page after hydration and stale toggle calls', () => {
    const persisted = { mode: 'canvas', surfaceMode: 'canvas' };
    const wrapper = ({ children }: { children: React.ReactNode }) => (
      <MemoryRouter initialEntries={[{ pathname: '/notes/s5-note', search: '?mode=canvas', state: persisted }]}>{children}</MemoryRouter>
    );
    const subject = renderHook(() => useSurfaceModeController({
      noteId: 's5-note', clearBlockSelection: vi.fn(), closeOverlay: vi.fn(), setSnapGuide: vi.fn(),
    }), { wrapper });
    expect(resolveActiveNoteCanvasMode(persisted.mode)).toBe('page');
    act(() => subject.result.current.resolveInitialSurfaceMode({
      blocks: [{ id: 'legacy', canvas_layout: { ...geometry, surface: 'canvas_workspace', boundary_role: 'crossing' } }],
      contentWidth: 650, loadedNoteId: 's5-note', loading: false,
    }));
    act(() => subject.result.current.toggleSurfaceMode());
    expect(subject.result.current.surfaceMode).toBe('page');
    expect(subject.result.current.surfacePolicy.isCanvasMode).toBe(false);
    expect(persisted).toEqual({ mode: 'canvas', surfaceMode: 'canvas' });
  });

  it('retains historical reads while refusing both old values before any client request', async () => {
    for (const fields of [
      { surface: 'canvas_workspace', boundary_role: 'outside' },
      { surface: 'formal_page', boundary_role: 'crossing' },
    ] as const) {
      const layout: BlockBoxLayout = { ...geometry, ...fields };
      const error = fields.surface === 'canvas_workspace' ? 'canvas_workspace_retired' : 'canvas_crossing_retired';
      expect(readStoredLayout({ id: 'legacy', canvas_layout: { ...layout } })).toMatchObject(fields);
      await expect(saveBlockCanvasPlacementForNote({ noteId: 's5-note', block: { id: 'b', placement_id: 'p' }, layout })).rejects.toThrow(error);
      for (const kind of ['paragraph_block_projection', 'shape', 'image', 'table', 'visual_connector']) {
        await expect(saveGenericCanvasObjectForNote({ noteId: 's5-note', objectId: kind, payload: { kind, placement: layout } })).rejects.toThrow(error);
      }
    }
    expect(api.put).not.toHaveBeenCalled();
  });

  it('blocks workspace regenerated by geometry and narrows final write DTOs without moving page/tray data', async () => {
    await expect(saveBlockCanvasPlacementForNote({
      noteId: 's5-note', block: { id: 'b', placement_id: 'p' },
      layout: { ...geometry, x: -12, coordinate_space: 'page_frame_local' },
    })).rejects.toThrow('canvas_workspace_retired');
    expect(api.put).not.toHaveBeenCalled();
    expect(() => requireCanvasPlacementWritePayload(geometry)).toThrow('canvas_surface_required');
    for (const surface of ['formal_page', 'tray'] as const) {
      const payload = { ...geometry, surface, boundary_role: surface === 'tray' ? 'outside' as const : 'inside' as const };
      expect(requireCanvasPlacementWritePayload(payload)).toBe(payload);
    }
  });
});
